### ISSUE TITLE
159 antigens 

### ISSUE THREAD

**Issue by Yuiceee** [csi-greifflab/Absolut#16]
Hello, 
I found that 159 antigens are not available in the data file. I mainly searched for pre-calculated CDRH3 sequences and energy information specific to certain antigens from RawBindingsHuman and RawBindingsMurine folders. However, I found that there are only 23 antigens in RawBindingsHuman and 103 antigens in RawBindingsMurine, while the paper mentions a total of 159 antigens. Could you please let me know where I can find information about the remaining antigens and their corresponding antibody database? Are they available.
Thank you!

**Comment by petouzeman** [comment]
Good morning,
Sorry for delay, we do not receive issue notifications, 
So, this is true, for the human, we only calculated human CDRH3s for 23 antigens as a control to compare murine and human
For Murine sequences, we indeed give for 159 antigens, but the "raw data" with the 7 million CDRH3s only got uploaded up to 103 antigens. However, for the full 159 antigens, we still give all the sequences with different classes of affinity, except for non-binders where we only give 500k sequences. This is available in the RawBindingPerClass folder: https://archive.sigma2.no/pages/public/datasetDetail.jsf?id=10.11582/2021.00063 for all 159 antigens
For a selection of binders and non-binders, you can directly look at Dataset1 
Hope it helps!
Best Wishes, 
Philippe
