### ISSUE TITLE
How to obtain pdb structure file from FinalBindings txt?

### ISSUE THREAD

**Issue by Y-H-Joe** [csi-greifflab/Absolut#19]
Thank you for your great work. I have a questoin.

for example, one row in the FinalBinidng txt:
1_03a	CAGPSTTVPYYFDYW	true	PSTTVPYYFDY	-78.32	132966-BDSRRLUUSL

the last one "132966-BDSRRLUUSL" should be the binding information. In this case, how can I get the antigen and antibody complex pdb from this information?

Thanks.

**Comment by petouzeman** [comment]
Hi, 
Sorry for delay, I don't receive notification on issues, 
there is a function for that, where you can give 132966-BDSRRLUUSL and get a PDB, you will get the discretized antigen and CDR3 in the PDB (but not the original antigen PDB)
PDB antigenID structureLigand AAseqLigand
in your case, (you will need to give the antigen) an example is:
./Absolut PDB 1ADQ_A 132966-BDSRRLUUSL CARTILGAGIN
this is indeed a hidden function that we didn't actively deploy, but you can use it
hope it helps!

**Comment by Y-H-Joe** [comment]
thanks !
