### ISSUE TITLE
discretization does not work

### ISSUE THREAD

**Issue by antonkulaga** [csi-greifflab/Absolut#2]
In the readme you wrote that discretization works without ui if I give a command like that:
```
Absolut discretize 5xmh AB 5.25 FuC
```
In reality it does not, it tries to connect to display that is weird for nonUI running mode.
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

/cromwell-executions/absolut_discretize/b552ae61-49f0-483b-a791-eeddc230b83b/call-absolut_discretize/execution/script: line 24:    16 Aborted                 (core dumped) Absolut discretize 5xmh AB 5.25 FuC
```
Your user interface is also broken, as it tries to run sh: 1: C:/MyPrograms/RasWin/RasWin.exe: not found
on Linux that does not make any sense.
I made the docker container for Absolut ( https://github.com/antonkulaga/airr-seq/tree/main/containers/absolut ). When I try without docker I build in a same way (with QT included).

**Comment by petouzeman** [comment]
With big apologies for delay, these issues stayed unnoticed, my bad.
Thanks for feedback! 
So, I rearranged some calling of libraries, will test that.
I also changed the Raswin call, well spotted
And I also added options to do discretization in command line.
In general, the spirit is to compile either no library at all (AbsolutNoLib) or all of them (including Qt), and then it is up to the user to use with or without the GUI. Now I make it more clear with new discretization steps without GUI at all (although the discretize command was working despite the GUI popping up, normally).
Also, thanks very much for the docker!
So now I hope this is solved, I will perform more tests to make it more QT free. There is also the option NO_QT but this is not my main focus too.
Have a nice day!

**Comment by demharters** [comment]
I'm ecountering the same issue when trying to run without gui

qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

**Comment by petouzeman** [comment]
Dear Demharters,

Thanks for the mail, I am not yet sure if you refer to a previous issue,

So, I can not reproduce your problem on a linux or MAC settings, so it's
hard to find a solution,
Could you maybe tell me what is your system, and the command you called for
AbsolutNoLib.
Also, are you using condo or a python env? I remember people having
problems of conflicts with Qt libraries from conda and that compiling from
an environment was automatically trying to use Qt in the compiling or the
loading, could it be something like this? In this case, maybe having a try
with a very simple system with no environment loaded could help!

Tell me if it works!
Best
Philippe Robert


Le jeu. 14 déc. 2023 à 13:44, demharters ***@***.***> a
écrit :

**Comment by demharters** [comment]
I found a fix.
The command runs without gui when I first do

`export QT_QPA_PLATFORM=offscreen`

PS: I am running it from native Ubuntu but within WSL2. I suspect it's because of X server. Need to set it up for Ubuntu in Windows..

**Comment by petouzeman** [comment]
Wow, thank you very much for sharing the fix!
Have a nice day,
Philippe

Le lun. 22 janv. 2024 à 10:28, demharters ***@***.***> a
écrit :
