### ISSUE TITLE
AbsoluNoLib fails on MacOS

### ISSUE THREAD

**Issue by zarifikram** [csi-greifflab/Absolut#23]
Reproduce : Run `make` in ./src

Output :                        
rm -f moc_predefs.h
rm -f compact.o lattice.o proteins.o receptorligand.o fastaffinity.o plot3d.o stopwatch.o md5.o zaptrackball.o zaprandom.o nucleotides.o distribution.o antigenLib.o epitope.o fileformats.o html.o importrepertoire.o motifFeatures.o selfEvo.o quality.o poolstructs.o delimain.o topology.o dlab.o
rm -f *~ core *.core
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o compact.o Ymir/compact.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o lattice.o Ymir/lattice.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o proteins.o Ymir/proteins.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o receptorligand.o Ymir/receptorligand.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o fastaffinity.o Ymir/fastaffinity.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o plot3d.o Ymir/plot3d.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o stopwatch.o Tools/stopwatch.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o md5.o Tools/md5.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o zaptrackball.o Ymir/zaptrackball.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o zaprandom.o Tools/zaprandom.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o nucleotides.o Tools/nucleotides.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o distribution.o Tools/distribution.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o antigenLib.o Absolut/antigenLib.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o epitope.o Absolut/epitope.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o fileformats.o Absolut/fileformats.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o html.o Absolut/html.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o importrepertoire.o Absolut/importrepertoire.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o motifFeatures.o Absolut/motifFeatures.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o selfEvo.o Absolut/selfEvo.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o quality.o Absolut/quality.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o poolstructs.o Absolut/poolstructs.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o delimain.o Absolut/delimain.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o topology.o Absolut/topology.cpp
g++ -c -pipe -Wreorder -std=c++11 -Wno-extra -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-implicit-int-float-conversion -O2 -w -D_REENTRANT -fPIC -DNOQT -DNO_LIBS -IAbsolute -I. -IYmir -I. -isystem /usr/include/libdrm  -o dlab.o Absolut/dlab.cpp
g++ -Wl,-O1 -o AbsolutNoLib compact.o lattice.o proteins.o receptorligand.o fastaffinity.o plot3d.o stopwatch.o md5.o zaptrackball.o zaprandom.o nucleotides.o distribution.o antigenLib.o epitope.o fileformats.o html.o importrepertoire.o motifFeatures.o selfEvo.o quality.o poolstructs.o delimain.o topology.o dlab.o   -lpthread   
ld: unknown option: -O1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [AbsolutNoLib] Error 1

**Comment by petouzeman** [comment]
Dear Zarifikram, 
Thanks for the issue report, I just got a Mac and tried, but I didn't get the error, 
It seems that some linkers do not accept the optimizing command "O1" but accept "o1", pretty stupid, while in my Mac now this is the opposite, if it is -O1 it works, but if it is -o1 I get your error: "clang: error: linker command failed with exit code 1 (use -v to see invocation)"
So basically I removed the optimization command on the linker side now, I don't think it will significantly make the program slower, since the G++ compiling steps are still -O2
So feel free to get the updated version just now and hopefully it should solve your problem,
And sorry for delay, I am not notified of issues, 
Best, 
Philippe

**Comment by zarifikram** [comment]
Thanks! That works as intended. Closing the issue.
