### ISSUE TITLE
download link for database results in 503 error

### ISSUE THREAD

**Issue by sacombs** [csi-greifflab/Absolut#7]
Download link is not working for the database.

**Comment by petouzeman** [comment]
Dear Sacombs, 
Sorry for delay, we don't get notifications for the issues, our bad, 
I will update the code in the following days, thanks for pointing out, 
Meanwhile you can access the database with 
https://ns9999k.webs.sigma2.no/10.11582_2021.00063/projects/NS9603K/pprobert/AbsolutOnline/
and for the structure files, use a link like this: https://ns9999k.webs.sigma2.no/10.11582_2021.00063/projects/NS9603K/pprobert/AbsolutOnline/Structures/0bdfb10d531f6c4c557b2d0dd3f2b8c4-10-11-db0516f09d29bca565e5d7d698eee5a4Structures.txt.zip
Best

**Comment by petouzeman** [comment]
actually, I thought that from the newer versions from April 2022, the links should be working, so I can not reproduce the problem, maybe tell more if you still have the problem with the latest version. 
Best

**Comment by sacombs** [comment]
It works now! Thanks for the update.
