### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by ElArkk** [csi-greifflab/Absolut#8]
Hi,
Very interesting work - thanks for making the code available! I can't seem to find any licence statement here or in the paper, what licence is being used for the code?

**Comment by petouzeman** [comment]
Dear ElArkk, 
Sorry for making you wait
Thanks for your interest! We had meeting about recently and actually didn't reach a decision, probably in a few days, will update you
Have a nice day!

**Comment by ElArkk** [comment]
Hey, I wanted to check back in here, have you come to a decision?

Best,
Arkadij

**Comment by petouzeman** [comment]
Dear ElArkk,
We are sadly still waiting for the technology transfer office to suggest something. (It's mainly about whether we make non-academic users pay for a license, and how do we retain rights to use it ourselves).
If you are in a rush, I would suggest to directly contact victor (victor.greiff [at] medisin.uio.no) and tell whether you are academic / industry, and which part you would like to use (the software, the database, both), and maybe he can come up with a specific fast solution before everything is settled.
I hope to get a license answer within let's say 2 weeks I will write down what happens as a reply here!
Have a nice day!
Philippe

**Comment by petouzeman** [comment]
Deat ElArkk, 
With a bit of delay (mega sorry), we have decided on a license.
You can have a look at it, it is the pdf in the main folder now, 
If you are not non-profit or non-academic, I would say the easiest would be to contact us with inven2 directly with an idea of what type of study you would like to do (discretization / using antigen library / accessing the database / using us to generate data for you) and we could agree on the best way to proceed!
Have a nice day,
Philippe
